In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
tf.__version__

'2.2.0'

In [3]:
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [38]:
import io
train_data = pd.read_csv(io.BytesIO(uploaded['Churn_Modelling.csv']))

In [39]:
train_data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [40]:
y = train_data['Exited']

In [41]:
train_data.drop('RowNumber', axis=1, inplace=True)

In [42]:
train_data.drop('CustomerId', axis=1, inplace=True)
train_data.drop('Surname', axis=1, inplace=True)
train_data.drop('Exited', axis=1, inplace=True)



In [43]:
x = train_data

In [44]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CreditScore      10000 non-null  int64  
 1   Geography        10000 non-null  object 
 2   Gender           10000 non-null  object 
 3   Age              10000 non-null  int64  
 4   Tenure           10000 non-null  int64  
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64  
 7   HasCrCard        10000 non-null  int64  
 8   IsActiveMember   10000 non-null  int64  
 9   EstimatedSalary  10000 non-null  float64
dtypes: float64(2), int64(6), object(2)
memory usage: 781.4+ KB


In [45]:
x = pd.get_dummies(x)

In [46]:
x

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 13 columns]

In [47]:
x.drop('Geography_France', axis=1,inplace=True)

In [48]:
x.drop('Gender_Female', axis=1,inplace=True)

In [49]:
from sklearn.model_selection import train_test_split
x_train, x_eval, y_train, y_eval = train_test_split(x,y,test_size=0.2,random_state=0)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_eval = sc.fit_transform(x_eval)

In [51]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [64]:
ann = tf.keras.models.Sequential()

In [65]:
ann.add(tf.keras.layers.Dense(units=11, activation='relu'))

In [66]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [67]:
ann.add(tf.keras.layers.Dense(units=1, activation='tanh'))

In [68]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [69]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 1.7950 - accuracy: 0.7381
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 1.1503 - accuracy: 0.7286
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7258 - accuracy: 0.7104
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6073 - accuracy: 0.7433
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5428 - accuracy: 0.7696
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5177 - accuracy: 0.7835
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5182 - accuracy: 0.7676
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5352 - accuracy: 0.7188
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5140 - accuracy: 0.7445
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5011 - accura

In [70]:
X = [[600,40,3,60000,2,1,1,50000,0,0,1]]

sc.transform(X)

array([[-0.52978695,  0.07611425, -0.739106  , -0.29407315,  0.80136281,
         0.66011376,  0.97628121, -0.86697328, -0.61433742, -0.57427105,
         0.8981563 ]])

In [71]:
print((ann.predict(X))>0.5)

[[ True]]


In [72]:
y_pred = ann.predict(x_eval)

In [83]:
y_pred

array([[0.35759106],
       [0.53278285],
       [0.09302142],
       ...,
       [0.13745113],
       [0.24793659],
       [0.22949187]], dtype=float32)

In [76]:
l = []
for pred in y_pred:
  if pred>0.5:
    l.append(1)
  else:
    l.append(0)  



In [84]:
l

[0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [80]:
y_eval = np.array(y_eval)

In [85]:
y_eval

array([0, 1, 0, ..., 0, 0, 0])

In [86]:
l = np.array(l)

In [88]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_eval,l)
print(cm)
accuracy_score(y_eval,l)

[[1490  105]
 [ 190  215]]


0.8525